<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ProviderQuery" targetNamespace="urn:hl7-org:v3"
                  xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:tns="urn:hl7-org:v3"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract"
                  xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy"
                  xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
    <wsdl:types>
        <xsd:schema targetNamespace="urn:hl7-org:v3/Imports">
            <xsd:import namespace="urn:hl7-org:v3" schemaLocation="ProviderQuery1.xsd"/>
            <xsd:import namespace="urn:bccdx" schemaLocation="ProviderQuery0.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="PRPM_IN306010UV_RequestContract">
        <wsdl:part name="PRPM_IN306010UV" element="tns:PRPM_IN306010UV">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="PRPM_IN306011UV_ResponseContract">
        <wsdl:part name="PRPM_IN306011UV" element="tns:PRPM_IN306011UV">
        </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="PRPM_AR300013UV">
        <wsdl:operation name="PRPM_IN306010UV">
            <wsdl:input name="PRPM_IN306010UV_RequestContract" message="tns:PRPM_IN306010UV_RequestContract"
                        wsaw:Action="urn:hl7-org:v3:PRPM_IN306010UV.NE20100705">
            </wsdl:input>
            <wsdl:output name="PRPM_IN306011UV_ResponseContract" message="tns:PRPM_IN306011UV_ResponseContract"
                         wsaw:Action="urn:hl7-org:v3:PRPM_IN306011UV.NE20100705">
            </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CustomBinding_PRPM_AR300013UV" type="tns:PRPM_AR300013UV">
        <wsp:PolicyReference URI="#CustomBinding_PRPM_AR300013UV_policy"/>
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="PRPM_IN306010UV">
            <soap:operation soapAction="urn:hl7-org:v3:PRPM_IN306010UV.NE20100705" style="document"/>
            <wsdl:input name="PRPM_IN306010UV_RequestContract">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="PRPM_IN306011UV_ResponseContract">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ProviderQuery">
        <wsdl:port name="CustomBinding_PRPM_AR300013UV" binding="tns:CustomBinding_PRPM_AR300013UV">
            <soap:address location="https://servicestest.bccdx.ca/RegistrySearch/ProviderQuery.svc"/>
        </wsdl:port>
    </wsdl:service>
    <wsp:Policy wsu:Id="CustomBinding_PRPM_AR300013UV_policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken RequireClientCertificate="false"/>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic256/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Strict/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SignedSupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:UsernameToken
                                sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssUsernameToken10/>
                            </wsp:Policy>
                        </sp:UsernameToken>
                    </wsp:Policy>
                </sp:SignedSupportingTokens>
                <sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy/>
                </sp:Wss11>
                <sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:MustSupportIssuedTokens/>
                        <sp:RequireClientEntropy/>
                        <sp:RequireServerEntropy/>
                    </wsp:Policy>
                </sp:Trust10>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
</wsdl:definitions>
