<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ClinicQuery" targetNamespace="urn:hl7-org:v3"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:tns="urn:hl7-org:v3"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:types>
        <xsd:schema targetNamespace="urn:hl7-org:v3/Imports">
            <xsd:import namespace="urn:hl7-org:v3" schemaLocation="ClinicQuery0.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="PRPM_IN406010UV_RequestContract">
        <wsdl:part name="PRPM_IN406010UV01" element="tns:PRPM_IN406010UV01">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="PRPM_IN406110UV_ResponseContract">
        <wsdl:part name="PRPM_IN406110UV01" element="tns:PRPM_IN406110UV01">
        </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="PRPM_AR400013UV">
        <wsdl:operation name="PRPM_IN406010UV01">
            <wsdl:input name="PRPM_IN406010UV_RequestContract" message="tns:PRPM_IN406010UV_RequestContract"
                        wsaw:Action="urn:hl7-org:v3:PRPM_IN406010UV01.NE20100705">
            </wsdl:input>
            <wsdl:output name="PRPM_IN406110UV_ResponseContract" message="tns:PRPM_IN406110UV_ResponseContract"
                         wsaw:Action="urn:hl7-org:v3:PRPM_IN406110UV01.NE20100705">
            </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CustomBinding_PRPM_AR400013UV" type="tns:PRPM_AR400013UV">
        <wsp:PolicyReference URI="#CustomBinding_PRPM_AR400013UV_policy"/>
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="PRPM_IN406010UV01">
            <soap:operation soapAction="urn:hl7-org:v3:PRPM_IN406010UV01.NE20100705" style="document"/>
            <wsdl:input name="PRPM_IN406010UV_RequestContract">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="PRPM_IN406110UV_ResponseContract">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ClinicQuery">
        <wsdl:port name="CustomBinding_PRPM_AR400013UV" binding="tns:CustomBinding_PRPM_AR400013UV">
            <soap:address location="https://servicestest.bccdx.ca/RegistrySearch/ClinicQuery.svc"/>
        </wsdl:port>
    </wsdl:service>
    <wsp:Policy wsu:Id="CustomBinding_PRPM_AR400013UV_policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken RequireClientCertificate="false"/>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic256/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Strict/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SignedSupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:UsernameToken
                                sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssUsernameToken10/>
                            </wsp:Policy>
                        </sp:UsernameToken>
                    </wsp:Policy>
                </sp:SignedSupportingTokens>
                <sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy/>
                </sp:Wss11>
                <sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:MustSupportIssuedTokens/>
                        <sp:RequireClientEntropy/>
                        <sp:RequireServerEntropy/>
                    </wsp:Policy>
                </sp:Trust10>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
</wsdl:definitions>
